pull_request_rules:
  - name: automatic backport of common pages
    conditions:
      - base=rolling
      - "files~=Governance|Contact|index|Marketing|ROSCon-Content|Roadmap|Releases|Feature-Ideas"
    actions:
      backport:
        branches:
          - foxy
          - eloquent
          - dashing

  - name: backport at reviewers discretion
    conditions:
      - base=rolling
      - "label=backport-all"
    actions:
      backport:
        branches:
          - foxy
          - eloquent
          - dashing

  - name: backport to foxy at reviewers discretion
    conditions:
      - base=rolling
      - "label=backport-foxy"
    actions:
      backport:
        branches:
          - foxy

  - name: backport to eloquent at reviewers discretion
    conditions:
      - base=rolling
      - "label=backport-eloquent"
    actions:
      backport:
        branches:
          - eloquent

  - name: backport to dashing at reviewers discretion
    conditions:
      - base=rolling
      - "label=backport-dashing"
    actions:
      backport:
        branches:
          - dashing
